name: Mordana Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Clean
      run: make clean
    - name: Build disk.img
      run: make disk.img
